name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install deps
        run: npm ci

      - name: Build (production)
        run: npm run build -- --configuration production --base-href "/gaelic_scoreboard/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/gaelic-scoreboard/browser
          publish_branch: gh-pages
